import { Box } from "@mui/material";

export default function TravelInfoView() {
  return (
    <>
      <Box>
        TravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPageTravelInfoViewPage
      </Box>
    </>
  );
}
